## Numpy

Is the main package for scientific computing in Python. It performs a wide variety of advance mathematical operations with high quality.

In [52]:
import numpy as np

The array object in Numpy is called `ndarray`  meaning 'n-dimensional array'

One of the common array type is: ('1-D'). A 1-D array represents a standard kust if values entirely in one dimension.

`NB: all the elements within the array are of the same type`

In [53]:
one_dimensional_arr = np.array([10, 12])
print(one_dimensional_arr)

[10 12]


### Numpy arrays:
One can create a 1-D array by simply using the function `array ()` which takes in a list of values as an argument and returns a 1-D.

In [54]:
# Create and print a Numpy array 'a' containing elements 1, 2, 3.

a = np.array([1, 2, 3])
print(a)

[1 2 3]


Arrays can also be implemented using `np.arange()`. This function will return an array of evenly spaced values within a given interval.

`NB: shift+tab : Is a powerful feature in Jupyter Notebook that allows you to access the documentation of any function`

In [55]:
# Create an array with 3 integers, starting from the default integer 0.

b = np.arange(3)
print(b)    


[0 1 2]


In [56]:
# Create an array that starts from the integer 1, ends at 20, incremented by 3. 

b = np.arange(1, 20, 3)

print(b)

[ 1  4  7 10 13 16 19]


`np.linspace()` allows you to create evenly space values in the intervals

The default types of data type from the `np.linspace()` function are floats because it is a floating point `(np.float64)`

`NB:` You can easily specify your data type using `dtype`

In [57]:
line_space_arr = np. linspace(0, 100, 5, dtype=int)

print(line_space_arr)

[  0  25  50  75 100]


In [58]:
char_arr = np.array(['Welcome to Math for ML!'])
print(char_arr)
print(char_arr.dtype)  # Prints the data type of the array which is a 23-character(23) unicode string(u) on a little endian architecture(<)

['Welcome to Math for ML!']
<U23


## More on NumPy arrays

One of the advantages of using NumPy is that you can easily create arrays with built-in functions such as: 

- `np.ones()` - Returns a new array setting values to one.
- `np.zeros()` - Returns a new array setting values to zero.
- `np.empty()` - Returns a new uninitialized array. 
- `np.random.rand()` - Returns a new array with values chosen at random.

## Multidimensional Arrays
- It has more that one column.

In [59]:
# Creare a 2 dimensional array(2-D)

two_dim_arr = np.array([[1, 2, 3], [4, 5, 6]])
print(two_dim_arr)

[[1 2 3]
 [4 5 6]]


An alternative way to crea a multidimensional array is by reshaping the initial 2-D array. Using `np.reshape()` you can rearrange elements of the previous array into a new shape.

In [60]:
# 1-D array

one_dim_arr = np.array([1, 2, 3, 4, 5, 6])

# Multidimensional array using reshape() method

multi_dim_arr = np.reshape(one_dim_arr, (2, 3))

print(multi_dim_arr)

[[1 2 3]
 [4 5 6]]


## Finding size, shape and dimension

The following attributes of the `ndarray` can be access as follow: 

- `ndarray.ndim` - stores the number dimensions of the array.
- `ndarray.shape` - Stores the shape of the array. Each number in the tuple denotes the lengths of each corresponding dimension
- `ndarray.size` - Stores the number of elements in the array.

In [61]:
# Dimension of the 2-D array multi_dim_arr

multi_dim_arr.ndim

2

In [62]:
# Shape of the 2-D array multi_dim_arr

multi_dim_arr.shape

(2, 3)

In [63]:
# Size of the array multi_dim_arr
# Returns total number of elements in the array

multi_dim_arr.size


6

3- Array math operations

NumPy allows you to perform elementwise addtion, substraction, multiplication and division for both 1-D and multidimensional arrays.

- The operations are performed using math symbol for each '+','-' and '*'

`NB: Addition of Python lists works completely differently as it would append the lists, thus making a longer list, in addition substraction and multiplication of Python lists do not work`

In [64]:
arr_1 = np.array([2, 4, 6])
arr_2 = np.array([1, 3, 5])

# adding two 1-D arrays

addtion = arr_1 + arr_2

print(addtion)

# Subtracting two 1-D arrays

subtraction = arr_1 - arr_2

print(subtraction)

# Multiplying two 1-D arrays

multiplication = arr_1 * arr_2

print(multiplication)

[ 3  7 11]
[1 1 1]
[ 2 12 30]


## Multiplying vector with a scalar(braodcasting)

- is the operations specifically on arrays of different shape

In [65]:
vector = np.array([1, 2])

vector * 1.6

array([1.6, 3.2])

## Indexing and Slicing

- Indexing is very useful as it allows you to select specific elements from an array. 
- It also lets you select entire rows/columns or planes as you'll see in future assignments for multidimensional arrays.

In [66]:
# Select the third element of the array.

a = ([1, 2, 3, 4, 5])

print(a[2])

3


NB: For multidimensional arrays of shape `n`, to index a specific element, you must input `n` indices, one for each dimension

In [67]:
# Indexing on a 2-D array

two_dim_arr = np.array([[1, 2, 3], [4, 5, 6],
[7, 8, 9]])

# Select element number 8 from the 2-D array using indices i, j.

print(two_dim_arr[2, 1])

8


### Slicing

- Gives you a sublist of elements that you specify from the array.

- The slice notation specifies a start and end value, and copies the list from start up to but not including the end(non-exclusive).

The syntax is 
`array[start:end:step]`

if no value is passed to start, it is assumed `start = 0`, if no values is passed to end, it is assumed that `end = length of array - 1` and if no value is passed to step, it is assumed `step = 1`

In [68]:
# Slice the array a to get the array [2, 3, 4]

slice_arr = a[1:4]
print(slice_arr)


[2, 3, 4]


In [69]:
# Slice the array a to get the array [1,2,3]
sliced_arr = a[:3]
print(sliced_arr)

[1, 2, 3]


In [70]:
# Slice the array a to get the array [3,4,5]
sliced_arr = a[2:]
print(sliced_arr)

[3, 4, 5]


In [71]:
# Slice the array a to get the array [1,3,5]
sliced_arr = a[::2]
print(sliced_arr)

[1, 3, 5]


In [72]:
# Note that a == a[:] == a[::]
print(a == a[:] == a[::])

True


In [73]:
# Slice the two_dim array to get the first two rows
two_dim = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

sliced_arr_1 = two_dim[0:2]

print(sliced_arr_1)

[[1 2 3]
 [4 5 6]]


In [74]:
# Similarily, slice the two_dim array to get the last two rows
sliced_two_dim_rows = two_dim[1:3]
print(sliced_two_dim_rows)

[[4 5 6]
 [7 8 9]]


In [75]:
sliced_two_dim_cols = two_dim[:,1]
print(sliced_two_dim_cols)

[2 5 8]


### Stacking #
- Is a feature of NumPy that leads to increased customization of arrays. It means to join two or more arrays, either horizontally or vertically, meaning that it is done along a new axis.


- `np.vstack()` - stacks vertically
- `np.hstack()` - stacks horizontally
- `np.hsplit()` - splits an array into several smaller arrays

In [76]:
a1 = np.array([[1,1],[2,2]])

a2 = np.array([[3,3],[4,4]])

print(f'a1: \n{a1}')
print(f'a2: \n{a2}')    

a1: 
[[1 1]
 [2 2]]
a2: 
[[3 3]
 [4 4]]


In [77]:
# Stack the arrays vertically

vert_stack = np.vstack((a1, a2))

print(vert_stack)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [78]:
# Stack the arrays horizontally

hor_stack = np.hstack((a1, a2))

print(hor_stack)

[[1 1 3 3]
 [2 2 4 4]]
